#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d X X X X X

bspc rule -a Emacs state=tiled

feh --bg-fill --randomize ~/Desktop/Wallps

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.57
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc node -t floating

# set to sticky 
bspc node -g sticky
